server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.49.3
eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
leyou:
  jwt:
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub
    cookieName: LY_TOKEN
